stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - autoparts
  script:
    - echo "=== DEPLOY START ==="

    - xcopy /E /I /Y * "C:\\Users\\HOME\\Desktop\\PPPI-Project-1\\AutoParts"

    - echo "=== DEPLOY COMPLETE ==="
